inscriptions/urls.py
from django.urls import path

from inscriptions import views

app_name = "inscriptions"
urlpatterns = [
    # path("", views.home_view),
    path("", views.InscriptionRequestListView.as_view(), name="list"),
    path("<int:pk>/", views.InscriptionRequestDetailView.as_view(), name="detail"),
    path("create/", views.InscriptionRequestCreateView.as_view(), name="create"),
    path("<int:pk>/update/", views.InscriptionRequestUpdateView.as_view(), name="update"),
    path("search/", views.InscriptionRequestSearchView.as_view(), name="search"),
    path("trainings/", views.CreateTraining.as_view(), name="create_training"),
]

makina/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("inscriptions.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

inscriptions/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.datetime_safe import date


class User(AbstractUser):
    pass


class AcademicTraining(models.Model):
    label = models.CharField(max_length=100)

    def __str__(self):
        return self.label


def date_must_be_future(value):
    if value and value <= date.today():
        raise ValidationError('The date must be future')


class InscriptionRequest(models.Model):
    candidat = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    date_creation = models.DateField(auto_now_add=True)
    date_demande = models.DateField(validators=[date_must_be_future], null=True)
    date_modification = models.DateField(auto_now=True)
    accepted = models.BooleanField(default=False)
    trainings = models.ManyToManyField(AcademicTraining, related_name="requests")

    def __str__(self):
        return f"Demande numéro {self.id}"

inscriptions/forms.py
from django import forms
from django.contrib.auth import get_user_model

from inscriptions.models import InscriptionRequest, AcademicTraining


class InscriptionCreateForm(forms.ModelForm):
    date_demande = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = InscriptionRequest
        fields = ("candidat", "trainings", "date_demande")

inscriptions/views.py
from django.forms import modelformset_factory
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, FormView
from django_filters.views import FilterView
from django.utils.translation import gettext_lazy as _

from inscriptions.filters import InscriptionRequestFilter
from inscriptions.forms import InscriptionCreateForm
from inscriptions.models import InscriptionRequest, AcademicTraining


def home_view(request):
    return HttpResponse("Bienvenue")


class CreateTraining(FormView):
    template_name = "inscriptions/academic_training_form.html"
    success_url = reverse_lazy("inscriptions:list")

    def get_form(self, form_class=None):
        TrainingFormSet = modelformset_factory(
            AcademicTraining, fields=("label",), extra=3
        )
        return TrainingFormSet(self.request.POST or None)


def add_training(request):
    TrainingFormSet = modelformset_factory(
        AcademicTraining, fields=("label", ), extra=3
    )
    formset = TrainingFormSet(request.POST or None)

    if formset.is_valid():
        formset.save()
        return HttpResponseRedirect(reverse("inscriptions:list"))

    return render(
        request, "inscriptions/academic_training_form.html", {"formset": formset}
    )


class InscriptionRequestListView(ListView):
    model = InscriptionRequest

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(accepted=False)
        return queryset.select_related("candidat").prefetch_related("trainings")


class InscriptionRequestDetailView(DetailView):
    model = InscriptionRequest


class InscriptionRequestCreateView(CreateView):
    template_name = "inscriptions/inscriptionrequest_form.html"
    form_class = InscriptionCreateForm
    success_url = reverse_lazy("inscriptions:list")


class InscriptionRequestUpdateView(UpdateView):
    model = InscriptionRequest
    template_name = "inscriptions/inscriptionrequest_form.html"
    form_class = InscriptionCreateForm
    success_url = reverse_lazy("inscriptions:list")


class InscriptionRequestSearchView(FilterView, ListView):
    model = InscriptionRequest
    template_name = "inscriptions/inscriptionrequest_search.html"
    filterset_class = InscriptionRequestFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(object_list=object_list, **kwargs)
        context_data["say_hello"] = _("Hello!")
        return context_data

inscriptions/templates/inscriptions/academic_training_form.html
{% extends 'base.html' %}

{% block content %}

  <form method="post" action="">
    {% csrf_token %}
    {{ form.management_form }}
    <table>
      {{ form.as_table }}
    </table>
    <button class="btn btn-primary">Soumettre</button>
  </form>

{% endblock %}

inscriptions/templates/inscriptions/inscriptionrequest_detail.html
{% extends "base.html" %}

{% block title %}
  {{ inscriptionrequest }}
{% endblock %}

{% block content %}
  <div class="container">
    <h1>{{ inscriptionrequest }}</h1>
    <a href="{% url 'inscriptions:update' inscriptionrequest.pk %}" class="btn btn-sm btn-warning">✎</a>

    <p>Cette demande à étée réalisée pour
      {% if inscriptionrequest.candidat.get_full_name %}
        {{ inscriptionrequest.candidat.get_full_name }}
      {% else %}
        {{ inscriptionrequest.candidat.username }}
      {% endif %}
      ({{ inscriptionrequest.candidat.email }})</p>

    <p>
      Cette demande à étée réalisée pour les formations :
    <ul>
      {% for training in inscriptionrequest.trainings.all %}
        <li>{{ training }}</li>
      {% endfor %}
    </ul>
    </p>


    <p>En date du {{ inscriptionrequest.date_creation }}</p>
    <p>Cette demande est {{ inscriptionrequest.accepted|yesno:"acceptée,pas acceptée" }}</p>
  </div>
{% endblock %}

inscriptions/templates/inscriptions/inscriptionrequest_form.html
{% extends "base.html" %}

{% block title %}
  {% if inscriptionrequest %}
    Modification de la demande {{ inscriptionrequest }}
  {% else %}
    Création d'une nouvelle demande
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container">

    {% if inscriptionrequest %}
      <h1>Modification de la demande {{ inscriptionrequest }}</h1>
    {% else %}
      <h1>Création d'une nouvelle demande</h1>
    {% endif %}

    <form action="" method="post" class="form">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Soumettre" class="btn btn-primary btn-success"/>

      {% if inscriptionrequest %}
        <a href="{% url 'inscriptions:detail' inscriptionrequest.pk %}" class="btn btn-primary btn-danger">Annuler</a>
      {% endif %}
    </form>
  </div>

{% endblock %}

inscriptions/templates/inscriptions/inscriptionrequest_list.html
{% extends "base.html" %}

{% block title %}
  Liste des demandes
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Liste des demandes</h1>

    <div class="d-grid gap-2 my-2">
      <a href="{% url 'inscriptions:create' %}" class="btn btn-primary">Faire une demande d'inscription</a>
    </div>

    {% if inscriptionrequest_list %}
      <ul class="list-group">
        {% for inscriptionrequest in inscriptionrequest_list %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <a
              href="{% url 'inscriptions:detail' inscriptionrequest.pk %}"
              class="text-decoration-none"
            >
              {{ inscriptionrequest.candidat }}
            </a>
            <ul>
              {% for training in inscriptionrequest.trainings.all %}
                <li>{{ training }}</li>
              {% endfor %}
            </ul>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>Aucunes demandes :(</p>
    {% endif %}
  </div>
{% endblock %}

inscriptions/templates/inscriptions/inscriptionrequest_search.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
  Liste des demandes
{% endblock %}

{% block content %}
  <div class="container">


    <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
      <input name="next" type="hidden" value="{{ redirect_to }}">
      <select name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
          <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
            {{ language.name_local }} ({{ language.code }})
          </option>
        {% endfor %}
      </select>
      <input type="submit" value="Go">
    </form>
    <h1>Liste des demandes</h1>
    <h2>{{ say_hello }}</h2>
    <a href="{% url 'inscriptions:create' %}" class="btn btn-primary mb-3">Ajouter une demande</a>

    <form action="" method="get" class="form">
      {{ filter.form.as_p }}
      <input type="submit" value="Soumettre" class="btn btn-primary btn-success"/>
    </form>

    {% if filter.qs %}
      <ul class="list-group">
        {% for demande in filter.qs %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="{% url 'inscriptions:detail' demande.pk %}"
               class="text-decoration-none"
            >
              {{ demande }}
            </a>
            <a href="{% url 'inscriptions:update' demande.pk %}" class="btn btn-sm btn-warning">✎</a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>{% trans "No requests" %}</p>
    {% endif %}
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    {% block title %}{% endblock %}
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
  {% include "header.html" %}
  <section>
    {% block content %}{% endblock %}
  </section>
  {% include "footer.html" %}
</body>
</html>

templates/footer.html
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted">&copy; 2022 UCL</p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
    </a>
  </footer>
</div>

templates/header.html
<div class="container">
  <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
      <span class="fs-4">Gestion des inscriptions à l'UCL</span>
    </a>

    <ul class="nav nav-pills">
      {% url 'inscriptions:list' as inscription_list %}
      <li class="nav-item"><a href="{% url 'inscriptions:list' %}" class="nav-link {% if request.path == inscription_list %}active{% endif %}" aria-current="page">Inscriptions</a></li>
      <li class="nav-item"><a href="/admin" class="nav-link" aria-current="page">Admin</a></li>
    </ul>
  </header>
</div>